server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc-secretsmanager:postgresql://testdb-pos-1.cluster-cjurcg0zx8s1.us-west-1.rds.amazonaws.com:5432/markting
    username: rds-db-credentials/cluster-YHHCJD32HYIA6WME5227AXG4C4/ulandmaster
    driverClassName: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
  redis:
    host: dev-rediscache.s1prrp.ng.0001.usw1.cache.amazonaws.com
    database: 1

  web:
    cors:
      allowOrigins:
        - https://*.youland.com
        - http://*.youland.com
        - https://*.youwork.us
        - http://*.youwork.us
    error:
      printStackTrace: true

